menyoo-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :restaurants , only: [:index, :show] do
      get "reviews", to: "restaurants#reviews", as: :reviews
      resources :dishes, only: [:index, :show]
      resources :bookings, only: [:index, :show, :new, :create, :update, :destroy]  do
        post 'pay', to: 'bookings#pay'
        get 'summary', to: 'bookings#summary'
        get 'checkin', to: 'bookings#checkin'
        resources :reviews, only: [:new, :show, :create, :destroy]
        resources :attendees, only: [:index, :new, :create, :destroy] do
          get 'accept', to: 'attendees#accept'
          resources :orders
        end
      end
  end

  resources :users, only: [:show, :edit] do
    get "reviews", to: "users#reviews", as: :reviews
    get "bookings", to: "users#bookings", as: :bookings
  end
end

menyoo-master/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :dish
  belongs_to :attendee

  before_save :default_values

  def default_values
    self.quantity = 1 if self.quantity.nil?
    self.ordered = false if self.ordered.nil?
  end
end

menyoo-master/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  # before_action :set_attendee, except: [:destroy]
  before_action :set_first_booking
  before_action :set_first_restaurant

  def index
    # @restaurant = @booking.restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])

    # @booking = @attendee.booking
    @booking = bookings_open_for_user_restaurant(current_user, @restaurant).last

    # @attendee = Attendee.find(params[:id])
    @attendee = Attendee.where(user: current_user, booking: @booking).last

    @orders = @attendee.orders.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    # @restaurant = @booking.restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])

    @dish = Dish.find(params[:order][:dish_id])

    # @booking = @attendee.booking
    @booking = bookings_open_for_user_restaurant(current_user, @restaurant).last

    @attendee = Attendee.where(user: current_user, booking: @booking).last
    @order.attendee = @attendee

    if @order.save
      respond_to do |format|
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
      # redirect_to restaurant_path(@restaurant)
    end
  end

  def edit
  end

  def update
  end

  def destroy
    order = Order.find(params[:id])
    order.delete
    @restaurant = Restaurant.find(params[:restaurant_id])
    @booking = Booking.find(params[:booking_id])
    @attendee = Attendee.find(params[:attendee_id])
    redirect_to restaurant_booking_attendee_orders_path(@restaurant, @booking, @attendee)
  end

end

def order_params
  params.require(:order).permit(:dish_id, :price, :quantity, :ordered)
end

# def set_attendee
#   @attendee = Attendee.find(params[:id])
# end

menyoo-master/app/views/orders/create.js.erb
// console.log("Create - Javascript");

orderDoneButton = document.querySelector("#order-done-dish-<%= @dish.id %>");
orderFormButton = document.querySelector("#order-form-dish-<%= @dish.id %>");

orderFormButton.classList.toggle("hide");
orderFormButton.classList.toggle("show");

orderDoneButton.classList.toggle("show");
orderDoneButton.classList.toggle("hide");

menyoo-master/app/views/orders/index.html.erb
<%  @page_title = "Your Order Summary" %>

<!-- Conditional formatting of the tab buttons -->
<% content_for(:tab_table_class, "tab_table_active") %>
<!-- end -->

<!-- Partial for the Modal -->
<div class="checkedin-popup hide">
  <%= render 'shared/checkedin' %>
</div>
<!-- end -->


<!-- Calculation the total for the orders -->
<% @order_total = 0 %>
<% @orders.each do |order|  %>
  <% @order_total = @order_total + order.dish.price %>
<% end %>
<!-- End Calculation -->

<div class="table-header">
  <h1><%= @restaurant.name %></h1>
  <p class="blue-font">Table for <%= @booking.date.to_s(:table_time) %></p>
</div>

<div class="button-area">
  <% if @attendee.payment == false  %>
    <%= link_to restaurant_path(@restaurant) do %>
      <button class = "button button-long">Add to Order</button>
    <% end %>
  <% end %>
</div>

<% @orders.each do |order|  %>

  <div class="card-box-shadow card-large">
    <div class="card-large-img">
      <%= cl_image_tag(order.dish.photo,width: 400, height: 300, crop: :fill) %>
    </div>
    <div class="card-large-content">
      <div class="card-order-add-remove">
        <h3><%= order.dish.name %></h3>

        <%= link_to ('<i class="fas fa-minus-circle button-delete"></i>').html_safe, restaurant_booking_attendee_order_path(@restaurant, @booking, @attendee, order),
          method: :delete,
          data: {confirm: "Are you sure?"}  %>
      </div>

      <p> <%= order.dish.description %></p>

      <div class="flex-between">
        <p>Quantity: 1</p>
        <p><%= humanized_money_with_symbol(order.dish.price) %></p>
        <p><i class="far fa-clock"></i> <%= order.dish.prep_time %></p>
      </div>
    </div>
  </div>
<% end %>

menyoo-master/app/views/orders/show.html.erb
<!-- Conditional formatting of the tab buttons -->
<% content_for(:tab_table_class, "tab_table_active") %>
<!-- end -->